export const dayOptions = [
  {value: "sunday", text: "Sunday"},
  {value: "monday", text: "Monday"},
  {value: "tuesday", text: "Tuesday"},
  {value: "wednesday", text: "Wednesday"},
  {value: "thursday", text: "Thursday"},
  {value: "friday", text: "Friday"},
  {value: "saturday", text: "Saturday"}
]


export const neighborhoodOptions = [
  {value: "Astoria", text: "Astoria"},
  {value: "Battery Park", text: "Battery Park"},
  {value: "Chelsea", text: "Chelsea"},
  {value: "East Village", text: "East Village"},
  {value: "Financial District", text: "Financial District"},
  {value: "Flatiron", text: "Flatiron"},
  {value: "Greenwich Village", text: "Greenwich Village"},
  {value: "Hell's Kitchen", text: "Hell's Kitchen"},
  {value: "Hoboken", text: "Hoboken"},
  {value: "Jersey City", text: "Jersey City"},
  {value: "Kips Bay", text: "Kips Bay"},
  {value: "Lower East Side", text: "Lower East Side"},
  {value: "Manhattan Valley", text: "Manhattan Valley"},
  {value: "Meatpacking District", text: "Meatpacking District"},
  {value: "Midtown East", text: "Midtown East"},
  {value: "Midtown West", text: "Midtown West"},
  {value: "Murray Hill", text: "Murray Hill"},
  {value: "NoHo", text: "NoHo"},
  {value: "Nolita", text: "Nolita"},
  {value: "North Massapequa", text: "North Massapequa"},
  {value: "North Bergen", text: "North Bergen"},
  {value: "Park Slope", text: "Park Slope"},
  {value: "SoHo", text: "SoHo"},
  {value: "South Orange", text: "South Orange"},
  {value: "South Slope", text: "South Slope"},
  {value: "South Street Seaport", text: "South Street Seaport"},
  {value: "South Village", text: "South Village"},
  {value: "Theater District", text: "Theater District"},
  {value: "TriBeCa", text: "TriBeCa"},
  {value: "Union Square", text: "Union Square"},
  {value: "Upper West Side", text: "Upper West Side"},
  {value: "West Village", text: "West Village"},
  {value: "Williamsburg", text: "Williamsburg"},
  {value: "South Williamsburg", text: "South Williamsburg"},
  {value: "Williamsburg - South Side", text: "Williamsburg - South Side"},
  {value: "Williamsburg - North Side", text: "Williamsburg - North Side"}

]
